name: grooming-detector
channels:
  - defaults
  - conda-forge
  - pytorch
  - huggingface
dependencies:
  - python=3.10
  - pandas
  - numpy
  - matplotlib
  - scikit-learn
  - pytorch
  - pip
  - pip:
      - datasets
      - transformers
      - evaluate
      - torch
      - discord.py
      - asyncio
